# Generated by Django 5.0.7 on 2024-07-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_US',
        ),
    ]
