# Generated by Django 5.0.7 on 2024-08-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_contact_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_US',
        ),
    ]
