# Generated by Django 5.0.7 on 2024-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.CharField(max_length=12)),
                ('ch_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
