# Generated by Django 5.0.7 on 2024-08-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('Quentity_Od', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
