# Generated by Django 5.0.7 on 2024-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
